# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_packet.proto\"\xe7\x01\n\nDataPacket\x12\x17\n\x0fsequence_number\x18\x01 \x01(\r\x12\x14\n\x0c\x63hunk_number\x18\x02 \x01(\r\x12\x14\n\x0ctotal_chunks\x18\x03 \x01(\r\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12+\n\x0bpacket_type\x18\x05 \x01(\x0e\x32\x16.DataPacket.PacketType\x12\x0f\n\x07\x63ommand\x18\x06 \x01(\t\x12\x1a\n\x10\x64\x61ta_port_number\x18\xd1\x86\x03 \x01(\r\")\n\nPacketType\x12\x08\n\x04\x44\x41TA\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x08\n\x04NACK\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_packet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAPACKET._serialized_start=22
  _DATAPACKET._serialized_end=253
  _DATAPACKET_PACKETTYPE._serialized_start=212
  _DATAPACKET_PACKETTYPE._serialized_end=253
# @@protoc_insertion_point(module_scope)
